stages:
  # - test
  - build 
  - deploy

# test project: 
#   stage: test
#   image: node:16.14.0
#   script:
#     - npm install
#     - npm test

build project: 
  stage: build
  image: node:16.14.0
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - build/ 

pages:
  image: node:16.14.0
  stage: deploy
  variables:
    GIT_STRATEGY: none        # Do not clone git repo
    NODE_ENV: production
  script:
    # Rename the CRA `build` folder to `public`
    - mv build public
  artifacts:
    paths:
      - public/
